{% set name = "batoid-rubin" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/batoid_rubin-{{ version }}.tar.gz
  sha256: 84041dcc545136e2d7661bc6aa5338f92c1175959dc2303b1c30ee0a8f750c41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - batoid >=0.4.2
    - ipywidgets
    - astropy
    - galsim
    - numpy
    - pyyaml
    - scipy
    - danish >=0.2.0
    - __unix

test:
  imports:
    - batoid_rubin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmeyers314/batoid_rubin
  summary: Rubin telescope models for batoid
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
