{% set name = "batoid-rubin" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/batoid_rubin-{{ version }}.tar.gz
  sha256: b6e8f44bca48da5f479e913903baac8f9563d2b14a941052c98d199c0c6cdb28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - batoid >=0.4.2
    - ipywidgets
    - astropy
    - galsim
    - numpy
    - pyyaml
    - scipy
    - danish >=0.2.0
    - __unix

test:
  imports:
    - batoid_rubin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmeyers314/batoid_rubin
  summary: Rubin telescope models for batoid
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
