{% set name = "batoid-rubin" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/batoid_rubin-{{ version }}.tar.gz
  sha256: 58623fec72ae6d7ada75a85f4abde34ddd1061966e9e3a52d1e479501d64cb63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - batoid >=0.4.2
    - ipywidgets
    - astropy-base
    - galsim
    - numpy
    - pyyaml
    - scipy
    - danish >=0.2.0
    - __unix
    - zenodo_get

test:
  imports:
    - batoid_rubin
  # fails and does not matter
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jmeyers314/batoid_rubin
  summary: Rubin telescope models for batoid
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - jmeyers314
